name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run iOS tests
      shell: bash
      run: xcodebuild test -project VerIDSDKIdentity.xcodeproj -scheme VerIDSDKIdentityiOS  -configuration Debug -destination "platform=macOS,variant=Mac Catalyst" | xcpretty

