name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run iOS tests
      shell: bash
      run: xcodebuild test -project VerIDSDKIdentity.xcodeproj -scheme VerIDSDKIdentityiOS -sdk iphonesimulator -configuration Debug -destination "platform=iOS Simulator,name=iPhone 11" | xcpretty

